# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Release.Name }}-nginx
#   labels:
#     app: nginx
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: 80
#               protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-service
# spec:
#   selector:
#     app.kubernetes.io/instance: {{ .Release.Name }}
#   type: {{ .Values.service.type }}
#   ports:
#     - protocol: {{ .Values.service.protocol | default "TCP" }}
#       port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}
#       nodePort: 30000

# nginx-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
# nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: nginx
